### ISSUE TITLE
Implement complete oauth workflow on other browsers

### ISSUE THREAD

**Issue by braxtonhall** [braxtonhall/library-thing#112]
[This](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/identity/launchWebAuthFlow) is supported by opera, firefox, edge, and probably brave.

We can also use chrome.manifest to get client_id and scopes, so yay to no duplication.

Seems like we'd need to do the access token caching on our own (similar to the original oath script we had)

**Comment by braxtonhall** [comment]
Apparently when auth fails we're supposed to use [this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/lastError#:~:text=The%20runtime.,the%20result%20of%20the%20function.) to find out why on some browsers

**Comment by braxtonhall** [comment]
Maybe [this](https://cloud.google.com/identity-platform/docs/web/chrome-extension) is useful?

**Comment by adirar111** [comment]
also [this?](https://github.com/Anarios/return-youtube-dislike/blob/84ede192b4821ebbbc177967a4bc9fd8e0a6243d/Extensions/combined/ryd.background.js#L23)

**Comment by adirar111** [comment]
https://github.com/PedroS11/twitch-live-extension/blob/ef3e1ca586b0f9d84e911964a8d79b36f3e18ef3/src/infrastructure/identityFlowAuth/indetityFlowAuth.ts#L20

**Comment by braxtonhall** [comment]
https://github.com/ademilter/Frame/blob/61aaecf96683a5cce8d8443682fc867483a06289/src/utils/get-token.js
