### ISSUE TITLE
manifest permissions warning

### ISSUE THREAD

**Issue by adirar111** [braxtonhall/library-thing#17]
new manifest complaint just dropped

![Screen Shot 2022-10-03 at 6 54 06 PM](https://user-images.githubusercontent.com/63937200/193717898-6a0570ca-7e14-4154-855e-ce3b84b292e3.png)

do we just remove `permissions` now that we have `host_permissions`? -- https://www.extension.ninja/blog/post/solved-permission-is-unknown-or-url-pattern-is-malformed/

**Comment by braxtonhall** [comment]
👀 which plugin is giving you these warnings?

**Comment by adirar111** [comment]
this is just chrome -- whenever i reload the extension, i see an errors button that takes me to these

![Screen Shot 2022-10-03 at 7 05 47 PM](https://user-images.githubusercontent.com/63937200/193719058-0633107e-9160-434e-bb68-451baa6863af.png)
