### ISSUE TITLE
Auto populate content warnings 

### ISSUE THREAD

**Issue by themaskedtaquito** [braxtonhall/library-thing#192]
If a tag is marked as needing a content warning, automatically populate the Comments section with the CW

**Comment by braxtonhall** [comment]
@themaskedtaquito what exactly do you imagine from this?

If it would just put one in secretly, it would be missing the actual content of the content warning, _and_ it would be doing things without the cataloguer's knowledge, which seems to be against the spirit of the kinds of changed we have so far.

One idea: if you try to leave and a content warning is needed, it prompts you with a screen that says "A content warning is required" and a text box to add your content warning.

OR: there is button that says "Check for CW". If no content warning is required, you get a notification saying "None needed". If one is required, you get a popup with a text box for entering the content of the content warning.

Actually we could do both. Does that seem reasonable?

cc: @librarianette

**Comment by themaskedtaquito** [comment]
@braxtonhall I think the first idea is good! Check for CW might be confusing because it sounds like it could be searching online information (like with PDFs), not necessarily checking the populated tags.

**Comment by braxtonhall** [comment]
Just an FYI @themaskedtaquito 
![image](https://user-images.githubusercontent.com/35436247/210970932-7ee9d741-0b7a-4965-8296-97a356641e80.png)
