### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'vbl-tag-input')

### ISSUE THREAD

**Issue by adirar111** [braxtonhall/library-thing#206]
![Screenshot 2022-11-23 at 10 24 42 PM](https://user-images.githubusercontent.com/63937200/203709550-101a1b92-970c-4fe6-a9dc-76e8ccdc91ca.png)

i think this is just `?.`-ing id in 

https://github.com/braxtonhall/library-thing/blob/dd927c328c9dfc3fe95799caa311683b5dc34a08/extension/ts/content/extensions/resize.ts#L36-L42

**Comment by braxtonhall** [comment]
_`sizeData`_ is `null`??????

**Comment by adirar111** [comment]
o wot i thought this was saying `element` was `null`

**Comment by braxtonhall** [comment]
no we're accessing `id` in `element`, which evaluated to `vbl-tag-input`... right? I have no idea how `sizeData` is `null`.

**Comment by braxtonhall** [comment]
what's in your `localStorage` for `"_resize-data"`?

**Comment by adirar111** [comment]
oop yeah you right hmmmmmmmmmmmm

**Comment by adirar111** [comment]
it doesn't exist lol -- this happened after navigating to the author page while testing on another chromium browser that i just loaded the extension into

**Comment by braxtonhall** [comment]
```
> JSON.parse(null)
null
```
are you kidding me

**Comment by braxtonhall** [comment]
I hate this language ~~sometimes~~
