### ISSUE TITLE
Issue with copying books

### ISSUE THREAD

**Issue by themaskedtaquito** [braxtonhall/library-thing#278]
One of the volunteers is unable to copy books after the extension update. The copy book button appears, but nothing happens when clicked. Paste book says there is no content to paste. They tried reinstalling a few times and still have the same issue. All I know for system information is they're on a Mac and are using the extension from the chrome store.

**Comment by braxtonhall** [comment]
Can you please ask them to press F12, Click on the "Console" tab, and screenshot any text in red, and paste it here?

**Comment by adirar111** [comment]
do they also by chance have multiple versions of the extension installed? they can check by going to the URL "chrome://extensions" and seeing if there's more than one "BetterLibraryThing"

**Comment by themaskedtaquito** [comment]
![IMG_20230120_154810_01](https://user-images.githubusercontent.com/15104789/213824792-7490f24b-4267-44fd-9bf0-e2130dde5cc3.jpg)

**Comment by braxtonhall** [comment]
Interesting. I've pushed a fix that should be out tomorrow.

Can you send me the book where this happened? It looks like it's missing a physical description. Maybe `librarything.com` is rolling out changes?

**Comment by braxtonhall** [comment]
Alright just took a look at the VanBlackLibrary account, and _none_ of the books have a physical description anymore. Meaning there is either an account setting we don't know about, or we're getting AB tested.

**Comment by braxtonhall** [comment]
`2.0.2` is out now on Firefox, and pending Google's approval on Chrome.

To update your extension to the latest version immediately, go to `chrome://extensions`, enable Developer Mode, and click `Update` to update all your extensions.

**Comment by braxtonhall** [comment]
For the curious, the real problem is here:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/35436247/213874028-c9996225-a101-4aaa-affa-718f21c65457.png">

LibraryThing users can disable physical description entirely
