### ISSUE TITLE
Migrate webpack to typescript

### ISSUE THREAD

**Issue by braxtonhall** [braxtonhall/library-thing#36]
Just so this
<img width="320" alt="image" src="https://user-images.githubusercontent.com/35436247/193997571-d9395f1d-ba5c-41b0-9995-e45fcd276aa1.png">
makes it to 100% 💆‍♀️

**Comment by braxtonhall** [comment]
<img width="330" alt="image" src="https://user-images.githubusercontent.com/35436247/194245351-578cbb7a-bf75-41d5-9e80-058229ebdb90.png">
noooooooo!!!!!

**Comment by adirar111** [comment]
:skull:

**Comment by adirar111** [comment]
![Screen Shot 2022-10-08 at 5 57 49 PM](https://user-images.githubusercontent.com/63937200/194732670-0bc61e70-cece-4570-857d-46915c5c96ea.png)

![so_good](https://user-images.githubusercontent.com/63937200/194732675-c757a77f-0531-41ad-ab8c-14f13c85d2bf.png)
