### ISSUE TITLE
New feature: automatically nested tags

### ISSUE THREAD

**Issue by librarianette** [braxtonhall/library-thing#68]
Hiiiiii thank you again!!

Is there any way to automatically add tags if one is added? It would be really useful for our genre and geography tags, which are nested and have multiple levels of specificity. For example, a book that is tagged as "K-3rd grade" should also automatically be tagged as "children's" or a book tagged as "Canada" should also automatically be tagged as "North America". 

Thanks guys <3

-Nola

**Comment by braxtonhall** [comment]
Oh yeah @adirar111 I think I forgot to mention: your Sheets API boutta come in CLUTCH because VBL already has the entire tag tree documented, and in GOOGLE SHEETS
