### ISSUE TITLE
New feature: automatically retrieved summaries

### ISSUE THREAD

**Issue by librarianette** [braxtonhall/library-thing#69]
okkkk this is the last thing I can think of for now— no rush and don't stress

just like you have the PDF function, is it possible to do the same for summaries but with the full text instead of a link? right now we tell people to pull a summary from goodreads, amazon, or the publisher's website. 

thank uuuu <3333

-Nola

**Comment by braxtonhall** [comment]
@librarianette 

Will start with just Goodreads.

When additional sources are found, should it:
- **Option A**: Use the first summary found,
- **Option B**: insert all summaries for the user to remove ones they don't like, or
- **Option C**: use the longest summary found?

**Comment by braxtonhall** [comment]
![Finding a Summary](https://user-images.githubusercontent.com/35436247/194742061-36d3b428-3fba-458e-b6f8-3f85331c66d8.gif)

Well something is progressing

**Comment by librarianette** [comment]
so beautiful!!!!

and I think that option B— reading multiple summaries helps the cataloger get a better feel of the book. that would also give them the option to combine them to optimize for search terms 

what do you think?
